// Printable parts of the chess rig, parametric.
// Generated by hardware/generate.py from chess_sim - edit there, not here.
// All dimensions in millimetres.

board_square      = 28.0;
board_overall     = 254.0;
arm_riser_height  = 60.0;
arm_base_x        = 110.9;
arm_base_y        = 72.0;
mast_plate        = [280.0, 140.0, 10.0];
mast_tube         = 30.0;
mast_height       = 600.0;
tray_slots        = 4;
tray_pitch        = 40.0;
tray_wall         = 3.0;
tray_depth        = 12.0;

module arm_riser() { cube([arm_base_x, arm_base_y, arm_riser_height], center = true); }

module mast_plate() { cube(mast_plate, center = true); }

// print in two halves if the bed is shorter than the mast
module mast_tube(length = mast_height / 2, wall = 2) {
    difference() {
        cube([mast_tube, mast_tube, length], center = true);
        cube([mast_tube - 2 * wall, mast_tube - 2 * wall, length + 1], center = true);
    }
}

module capture_tray() {
    pocket = tray_pitch - tray_wall;
    difference() {
        cube([tray_pitch + 2 * tray_wall,
              tray_slots * tray_pitch + 2 * tray_wall,
              tray_depth + tray_wall], center = true);
        for (i = [0 : tray_slots - 1])
            translate([0,
                       (i - (tray_slots - 1) / 2) * tray_pitch,
                       tray_wall])
                cube([pocket, pocket, tray_depth + 1], center = true);
    }
}

arm_riser();
translate([0, 120, 0]) mast_plate();
translate([0, 220, 0]) mast_tube();
translate([0, 340, 0]) capture_tray();
